### ISSUE TITLE
Documentation ?

### ISSUE THREAD

**Issue by GnubiBORED** [kyan001/ping3#16]
Im trying to make a ping and check the status of the ping, if was sucesfull etc But i cannot find doc about library, is there anywhere?

im doing like this, but i think its a horrible way
```
import ping3
ping3.DEBUG = True
s = ping3.ping('192.168.1.198')

if type(s) == float:
    print("Host Up")
else:
    print("Host down")


```

**Comment by kyan001** [comment]
It's a pretty simple lib so I do not write the doc. But I keep update the [README.md](https://github.com/kyan001/ping3/blob/master/README.md) file as the manual. You can check all the usages and parameters in it. If there is a doc for ping3, then the README file is it.

For the code you provided, you can use `if s` to check the result.
```python
import ping3
s = ping3.ping('192.168.1.198')
if s:  # s is not None
    print("Host Up")
else:  # s is None
    print("Host Down")
```
or you can use a more pythonic way to do this
```python
import ping3
HOST = '192.168.1.198'
pong = ping3.ping(HOST)
print("Host Up" if pong else "Host Down")
```
