### ISSUE TITLE
Intervals between pings

### ISSUE THREAD

**Issue by baltasvejas** [kyan001/ping3#17]
It would be good to have possibility to set intervals between pings.
example: interval=10 [ms]
verbose_ping('example.com', unit='ms', count=100, interval=10)

**Comment by kyan001** [comment]
Hi @baltasvejas ,

Sorry for the waitings.
The interval thing would be a good idea. I am working on it. It should be available at version 2.5.x.

Thanks.

**Comment by kyan001** [comment]
Hi @baltasvejas .

Interval is supported on v2.5.1. you can use `verbose_poing(..., interval=10)` to set the interval to 10 seconds.
Also, `$ ping3 ... -i/--interval 10` will work.

Thanks for the suggestion.
