### ISSUE TITLE
Packet payload size

### ISSUE THREAD

**Issue by perdachillo** [kyan001/ping3#21]
Сhanging ICMP packet payload size from 0 to 16:
```
for pack_len in range(0,16):
	pack = ping(dest_ip, size=pack_len)
```
gives the same frame length (50 bytes) and same ICMP payload (8 bytes) in WireShark.

**Comment by kyan001** [comment]
@perdachillo 

There is a minimal size of ping packet, which should be the size of time in payload (8 Bytes), plus the size of ICMP header (8 Bytes). So the size parameter should be at least 16 to make it work. Can you try 17 or 32, see if it works? The default padding char is "Q".

The "same ICMP payload (8 bytes)" you mentioned is a time int in the form of double. Whatever you put in ICMP payload, destination host should send them back untouched. So when we got a pong packet, we can know the exactly sent time by its ICMP payload.

Thanks for the feedback, if the "size" thing still doesn't work, let me know.

**Comment by kyan001** [comment]
@perdachillo 
I just found a bug of the size thing. The min value of size should be 8 instead of 16. I should not substract the size of ICMP HEADER. This will fixed in 2.4.7, and I will add some notes to the comments. 
Thanks again for the feedback.

**Comment by perdachillo** [comment]
16 and 32 works fine.
But I wanted to generate a frame similar to:
`ping 192.168.88.242 -f -l 0`
In this case, the packet length is 42 bytes and there is no ICMP payload:
![ScreenShot416](https://user-images.githubusercontent.com/62994649/78146158-73538500-743a-11ea-85fd-560e4db61509.png)
Can I generate a similar frame using ping3?
Thanks.

**Comment by kyan001** [comment]
> 17 and 32 works fine.
> But I wanted to generate a frame similar to:
> `ping 192.168.88.242 -f -l 0`
> In this case, the packet length is 42 bytes and there is no ICMP payload:
> ![ScreenShot416](https://user-images.githubusercontent.com/62994649/78146158-73538500-743a-11ea-85fd-560e4db61509.png)
> Can I generate a similar frame using ping3?
> Thanks.

Hi,

Currently what you can do, is set the size lower than 8 (for example: 0). Doing this will make the ICMP payload size = 8Bytes. Ping3 need the 8 bytes of payload to calculate the time spent. So I guess 50 bytes is the min of the packet size.
