### ISSUE TITLE
ping3 multiprocessing buggy

### ISSUE THREAD

**Issue by joelfranco** [kyan001/ping3#23]
Hello,
I think that ping3 is buggy when used with multiprocess Process with start method "fork".
Look the code and result:

```
def doping2(host):
    while True:
        delay = ping3.ping(host)
        import time; time.sleep(1)
        print(host, delay)

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    args = p.parse_args()

    #mp.set_start_method('spawn')

    hosts = ['a.dns.br', 'b.dns.br']
    for i in hosts:
        p = mp.Process(target=doping2, args=(i,))
        p.start()
```
Result in buggy result (the hosts do not have similar delay times):
```
root@fat-x220-c577d2:/usr/local/bin# ping123
b.dns.br 0.051039695739746094
a.dns.br 0.05103778839111328
b.dns.br None
a.dns.br None
b.dns.br 0.054898738861083984
a.dns.br 0.054898738861083984
a.dns.br 0.05213785171508789
b.dns.br 0.05213785171508789
```

But if i insert:
`mp.set_start_method('spawn')`
 
it runs fine (actually a.dns.br is blocked):
```
root@fat-x220-c577d2:/usr/local/bin# ping123
b.dns.br 0.051796674728393555
b.dns.br 0.05194592475891113
b.dns.br 0.05153298377990723
b.dns.br 0.05203509330749512
a.dns.br None
b.dns.br 0.05774235725402832
b.dns.br 0.0719301700592041
b.dns.br 0.06660127639770508
b.dns.br 0.06898736953735352
b.dns.br 0.05692934989929199
a.dns.br None
```
Is it a bug or an expected result?

Thanks :-)
joel

**Comment by kyan001** [comment]
Hi @joelfranco 

After investigation, this one is a bug. When using `multiprocessing` module, `threading.currentThread().ident` will retrive the same `thread_id`, thus they have identical `ICMP_ID` which makes they are hard to distinguish from each other.

I will make sure that they don't have the same `ICMP_ID` when being started by either multiprocess or multithread.

Sorry for the inconvience, and thank you for the feedback.

**Comment by joelfranco** [comment]
> Hi @joelfranco
> 
> After investigation, this one is a bug. When using `multiprocessing` module, `threading.currentThread().ident` will retrive the same `thread_id`, thus they have identical `ICMP_ID` which makes they are hard to distinguish from each other.
> 
> I will make sure that they don't have the same `ICMP_ID` when being started by either multiprocess or multithread.
> 
> Sorry for the inconvience, and thank you for the feedback.

**Comment by joelfranco** [comment]
i closed it by mistake. Thank you

**Comment by kyan001** [comment]
Hi @joelfranco 

I just updated ping3 to 2.6.2. Hopefully it will fix the bug.
Can you give it a try and tell me if it works?
Upgrade: `python3 -m pip install -U ping3` or `pip3 install -U ping3`

Thanks

**Comment by joelfranco** [comment]
Hello Kyan,

Yes it worked :-)

Thank you a lot.

joel

Em 09/05/2020 10:34, Kyan escreveu:
