### ISSUE TITLE
Timeout does not time out at set interval & does not return value in milliseconds.

### ISSUE THREAD

**Issue by GerElef** [kyan001/ping3#29]
ping does not timeout at set interval: I have set timeout = 1 and it still takes 4+ seconds to timeout. This happens when my router drops the DSL connection or when I shut down manually windows 10 wifi (which is the interface I'm using).

`
Encountered unexpected PingError Request timeout for ICMP packet. (Timeout=4s) when pinging cloudflare1.1.1.1
[DEBUG] Request timeout for ICMP packet. (Timeout=4s)
[DEBUG] Function Called: ping('1.0.0.1')
[DEBUG] Function Called: send_one_ping({'sock': <socket.socket fd=472, family=AddressFamily.AF_INET, type=SocketKind.SOCK_RAW, proto=1>, 'dest_addr': '1.0.0.1', 'icmp_id': 62784, 'seq': 0, 'size': 56})
[DEBUG] Destination Address: '1.0.0.1'
[DEBUG] Destination Address: 1.0.0.1
[DEBUG] Sent ICMP Header: {'type': 8, 'code': 0, 'checksum': 19040, 'id': 62784, 'seq': 0}
[DEBUG] Sent ICMP Payload: b'A\xd7\xdb\xdd\xe5\x86\x15\x83QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ'
[DEBUG] Function Returned: send_one_ping -> None
[DEBUG] Function Called: receive_one_ping({'sock': <socket.socket fd=472, family=AddressFamily.AF_INET, type=SocketKind.SOCK_RAW, proto=1, laddr=('0.0.0.0', 0)>, 'icmp_id': 62784, 'seq': 0, 'timeout': 4})
[DEBUG] Timeout time: Sat Sep 26 20:17:14 2020
[DEBUG] Timeout left: 4.00s
`

![Screenshot_1](https://user-images.githubusercontent.com/44060598/94346517-cd25b800-0035-11eb-8fa9-57762d0d8a4c.png)
![Screenshot_2](https://user-images.githubusercontent.com/44060598/94346518-ceef7b80-0035-11eb-8be5-a08ad390fef9.png)

EDIT: Forgot to mention that, because of this bug, I've noticed occurances where the program returns values way beyond 1000 (which should be the theoretical maximum value to return, within a degree of accuracy)

Also, does not return the value in milliseconds (with the same settings as above), requiring me to convert by multiplying by 1000.

![image](https://user-images.githubusercontent.com/44060598/94346627-97cd9a00-0036-11eb-9d79-e514ee38f5d7.png)

**Comment by kyan001** [comment]
Hi @GerElef ,

From that debug log, it seems the keyword arguments are not passed to the ping function.
I tested on my Linux server with ping3 2.6.6, all tests are passed.
Could you please double check your code where you pass the arguments to ping3.ping()
or you can just paste more of your code here, let's figure this out.

**Comment by GerElef** [comment]
I'm using ping3 version 2.6.6 as well.

Here is the full python module I'm using to ping servers. Servers.json is an external file, that loads 4 IPs and 4 dns resolved names of said IPs. The method in question is ping(self, server). Note that I'm running on the latest version of Windows 10. Interface used is the correct IP of a corresponding interface of my computer (I've used the same network interface IP on Python & Java sockets with no issues). 

I should probably note that the static variable UPPER_LIMIT has no other code occurrences outside of this class, so it's not edited whatsoever. I'll post some more logs at the end.


    import ping3
    from ping3 import ping
    from errors import PingError, Timeout
    
    from db.dao import Dao
    
    ping3.EXCEPTIONS = True
    
    class StabilityTester:
        UPPER_LIMIT = 1000 #upper limit in ms
        SLEEP_TIME = 1 #sleep time between calls in seconds -- ideally should be the same as upper limit
    
        def __init__(self, src_addr):
            with open("servers.json", 'r', encoding="utf-8") as file:
                data = load(file)
    
            self.servers = data[0]
            self.servers_readable = data[1]
            self.local_history = []
    
            self.db = Dao()
            self.interface = src_addr
    
            for _ in self.servers:
                self.local_history.append(0)
    
            if len(self.servers) != len(self.servers_readable):
                raise ServerHostNameMismatchException()
    
        def ping_forever(self):
            while True:
                self.loop_servers()
    
        def ping_with_event(self, evt):
            while True:
                if evt.is_set():
                    break
                self.loop_servers()
    
        def loop_servers(self):
            tts = StabilityTester.SLEEP_TIME
    
            for i in range(len(self.servers)):
                try:
                    ms = ping(self.servers[i])
                    int_ms = int(ms * 1000)
                    r_ms = round(ms,3)
    
                    time_left = tts - r_ms if r_ms < tts else 0
    
                    self.db.timestamp(int_ms, StabilityTester.UPPER_LIMIT,
                                      self.servers, self.servers_readable,
                                      self.interface)
    
                    print(f"Server Name: {self.servers_readable[i]}\n"
                          f"\t\tReplied in: {int_ms}ms\n"
                          f"\t\tPing Variation: {int_ms - self.local_history[i]}ms")
    
                    self.local_history[i] = int_ms
    
                    sleep(time_left)
    
                except Timeout:
                    self.db.timestamp(0, StabilityTester.UPPER_LIMIT,
                                      self.servers, self.servers_readable,
                                      self.interface, True)
    
                    print(f"Server Name: {self.servers_readable[i]}\n"
                          f"\t\tConnection timed out.")
    
                except PingError as pe:
                    print(f"Encountered unexpected PingError {pe} when pinging {self.servers_readable[i]}")
                except Exception as e:
                    print(f"Encountered unexpected generic exception {e}")
    
    
        def ping(self, server):
            #timeout should be in seconds, not milliseconds
            timeout = int(StabilityTester.UPPER_LIMIT / 1000)
    
            return ping(server, interface = self.interface, unit = 'ms', timeout = timeout)
    
    
    class ServerHostNameMismatchException(Exception):
        pass

**Comment by GerElef** [comment]
On further investigation: idle threw exception invalid argument for "interface" positional argument, as I am on windows.
**On my project, this did not throw an exception.** I changed the argument to src_addr as is recommended and required on windows. Note, that this did not fix my issue.

**Comment by GerElef** [comment]
Apparently there was a namespace collision. Entirely my fault, and not the dependency's. Thanks for taking the time, I appreciate it and your work.
