### ISSUE TITLE
[Errno 1] Operation not permitted 

### ISSUE THREAD

**Issue by leogitpro** [kyan001/ping3#36]
On lubuntu 21.04, Python 3.9.4 ping3 2.7.0
always error: Operation not permitted 
IDE: pycharm, venv

**Comment by kyan001** [comment]
> On lubuntu 21.04, Python 3.9.4 ping3 2.7.0
> 
> always error: Operation not permitted 
> 
> IDE: pycharm, venv

Lunix still need run in root privilege.
