### ISSUE TITLE
Could we add the function that ping multiple targets like Fping?

### ISSUE THREAD

**Issue by sshuangliu** [kyan001/ping3#44]
AS we cannot use Fping in windows as in Linux, but It is necessary to use it in windows, so why don't add a new feature in this python lib, it can be inputted a ip list or ip file then test ip efficiently and return an results list.

there are no another ping related libs so popular like this , if it can support ping multiple targets ,it will be more useful and popular.

thanks

**Comment by kyan001** [comment]
Hi @sshuangliu,

Currently I don't have plan for multiple targets ping. As I see it, Fping is more like a module which based on ping not comes with ping. That means Fping should not be a part of ping, and should packed as a package/module.

If you has some spare time, feel free to create a new python3 package call `Fping3` and make ping3 become its dependency. I will see if there anything I can help.

Thank you for your feedback.
