### ISSUE TITLE
Randomly says no response

### ISSUE THREAD

**Issue by Midnex** [kyan001/ping3#45]
I haven't been able to figure out why, but sometimes after a few thousands pings (the case below 18xx), Ping3 reports no response, then 5 seconds later reports a response. When testing we had multiple terminals open all pinging at the same time, and only Ping3 comes back and says failed.

[DEBUG] Function called: ping('192.168.1.10')
[DEBUG] Function called: send_one_ping({'sock': <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=1, laddr=('0.0.0.0', 0)>, 'dest_addr': '192.168.1.10', 'icmp_id': 30536, 'seq': 0, 'size': 56})
[DEBUG] Destination address: '192.168.1.10'
[DEBUG] Destination IP address: 192.168.1.10
[DEBUG] Sent ICMP header: {'type': 8, 'code': 0, 'checksum': 5209, 'id': 30536, 'seq': 0}
[DEBUG] Sent ICMP payload: b'A\xd8bc\x15\x89\x12\xfaQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ'
[DEBUG] Function returned: send_one_ping -> None
[DEBUG] Function called: receive_one_ping({'sock': <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=1, laddr=('0.0.0.0', 1813)>, 'icmp_id': 30536, 'seq': 0, 'timeout': 4})
[DEBUG] Timeout time: Mon Nov  8 12:45:14 2021 (1636404314.1421816)
[DEBUG] Timeout left: 4.00s
[DEBUG] Request timeout for ICMP packet. (Timeout=4s)
[DEBUG] Function returned: ping -> None
[DEBUG] Function called: ping('192.168.1.10')
[DEBUG] Function called: send_one_ping({'sock': <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=1, laddr=('0.0.0.0', 0)>, 'dest_addr': '192.168.1.10', 'icmp_id': 30536, 'seq': 0, 'size': 56})
[DEBUG] Destination address: '192.168.1.10'
[DEBUG] Destination IP address: 192.168.1.10
[DEBUG] Sent ICMP header: {'type': 8, 'code': 0, 'checksum': 40879, 'id': 30536, 'seq': 0}
[DEBUG] Sent ICMP payload: b'A\xd8bc4"i\nQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ'
[DEBUG] Function returned: send_one_ping -> None
[DEBUG] Function called: receive_one_ping({'sock': <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=1, laddr=('0.0.0.0', 1814)>, 'icmp_id': 30536, 'seq': 0, 'timeout': 4})
[DEBUG] Timeout time: Mon Nov  8 12:47:16 2021 (1636404436.5383997)
[DEBUG] Timeout left: 4.00s
[DEBUG] Received time: Mon Nov  8 12:47:12 2021 (1636404432.5930107))
[DEBUG] Received ICMP header: {'type': 0, 'code': 0, 'checksum': 6114, 'id': 1814, 'seq': 0}
[DEBUG] Received ICMP payload: b'A\xd8bc4"i\nQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ'
[DEBUG] Received sent time: Mon Nov  8 12:47:12 2021 (1636404432.537661)
[DEBUG] Function returned: receive_one_ping -> 0.05534958839416504
[DEBUG] Function returned: ping -> 0.05534958839416504
[DEBUG] Function called: ping('192.168.1.10')
[DEBUG] Function called: send_one_ping({'sock': <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=1, laddr=('0.0.0.0', 0)>, 'dest_addr': '192.168.1.10', 'icmp_id': 30536, 'seq': 0, 'size': 56})
[DEBUG] Destination address: '192.168.1.10'
[DEBUG] Destination IP address: 192.168.1.10
[DEBUG] Sent ICMP header: {'type': 8, 'code': 0, 'checksum': 47997, 'id': 30536, 'seq': 0}
[DEBUG] Sent ICMP payload: b'A\xd8bc4fL\xf8QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ'
[DEBUG] Function returned: send_one_ping -> None
[DEBUG] Function called: receive_one_ping({'sock': <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=1, laddr=('0.0.0.0', 1815)>, 'icmp_id': 30536, 'seq': 0, 'timeout': 4})
[DEBUG] Timeout time: Mon Nov  8 12:47:17 2021 (1636404437.5993645)
[DEBUG] Timeout left: 4.00s
[DEBUG] Received time: Mon Nov  8 12:47:13 2021 (1636404433.6540964))
[DEBUG] Received ICMP header: {'type': 0, 'code': 0, 'checksum': 13231, 'id': 1815, 'seq': 0}
[DEBUG] Received ICMP payload: b'A\xd8bc4fL\xf8QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ'
[DEBUG] Received sent time: Mon Nov  8 12:47:13 2021 (1636404433.5984478)
[DEBUG] Function returned: receive_one_ping -> 0.0556485652923584
[DEBUG] Function returned: ping -> 0.0556485652923584

When I am pinging I am looking for a response, and if one I am returning True, otherwise False.
`return[False if ping3.ping(host) == None else True][0]`

Any thoughts on what may be causing it and how I can go about fixing it?

**Comment by kyan001** [comment]
Hi @Midnex,

From the log I cannot see any abnormal activities. Can you copy and paste the log when the error happening? You can catch the exception raise when it returns timeout with EXCEPTIONS flag set.

Looking forward to your reply.

**Comment by Midnex** [comment]
I will set it up tomorrow to run and get your the full log.

**Comment by Midnex** [comment]
Sorry I haven't gotten back to this. Been extremely busy lately. It is not forgotten.
