### ISSUE TITLE
github云不能ping吗？

### ISSUE THREAD

**Issue by vpei** [kyan001/ping3#46]
github云不能ping吗？测试每个IP结果返回都是None

**Comment by vpei** [comment]
> 有 DEBUG = True 时的输出吗？贴一些

估计不是程序的问题，应该是系统问题。用简单的ping，也是只能ping本机，其他IP都不行。

PING 127.0.0.1 (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.049 ms
--- 127.0.0.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.049/0.049/0.049/0.000 ms

PING 8.8.8.8 (8.8.8.8): 56 data bytes
--- 8.8.8.8 ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

PING github.com (192.30.255.113): 56 data bytes
--- github.com ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss

**Comment by kyan001** [comment]
OK. If you met any problem about ping3, feel free to open an issue.
