### ISSUE TITLE
strange error :)

### ISSUE THREAD

**Issue by shkabatur** [kyan001/ping3#50]
Thanks a lot for the module! 👍 

When i run the following code:
(python 3.10 on windows 10)
```
from ping3 import ping
from concurrent.futures import ThreadPoolExecutor

hosts = [
    'google.com',
    'yandex.ru',
    'telegram.org',
    '172.16.9.11',
    '127.0.0.1',
    ]

p = ThreadPoolExecutor(max_workers=len(hosts))

for result in p.map(ping, hosts, [1] * len(hosts)):
    print(result)
```
I get an error:

```
pargs = ", ".join("{}".format(arg) if isinstance(arg, str) else arg for arg in args) 
TypeError: sequence item 1: expected str instance, int found

file: __init__.py line:80 in function  _func_logger
```
for myself i solved it by replacing from
`pargs = ", ".join("{}".format(arg) if isinstance(arg, str) else arg for arg in args) `
to
`pargs = ", ".join("'{}'".format(arg) for arg in args)`

And the second assumption is that the code inside wrapper should be run only in debug mode.

Thanks for the work you've done! :)

**Comment by kyan001** [comment]
thanks for the report. This bug is just fixed in version 4.0.2.
