### ISSUE TITLE
errors.py bug

### ISSUE THREAD

**Issue by zhangyun173** [kyan001/ping3#54]
class DestinationHostUnreachable(DestinationUnreachable):
mybe this?
class DestinationHostUnreachable(PingError):
or 
super().__init__(ip_header,icmp_header)

bug test in py3.9 use code
 errors.DestinationHostUnreachable(ip_header=ip_header, icmp_header=icmp_header)

**Comment by kyan001** [comment]
This bug is fixed on version 4.0.1. Thanks for your report!
