### ISSUE TITLE
icmp packetsize(length 200) is too big for some network!

### ISSUE THREAD

**Issue by kivis-online** [kyan001/ping3#6]
hi,I have an issue in my network, Administrator limit the ICMP packet size for security，I think the ping3 Whether Reduce the packetsize to length 64?, or make the packet size as a  parameter for ping3.ping  function.

**Comment by kyan001** [comment]
I'm looking into it.

**Comment by kyan001** [comment]
Added in version 2.0.0. Please check the readme file for usage.
