### ISSUE TITLE
Patch failure due to "different line endings"

### ISSUE THREAD

**Issue by lordofire** [kyan001/ping3#62]
Hi, I'm using the pypi source distribution and is applying some patches on top of it on Linux, more specifically it is Ubuntu 18.04. However, I just found out that the source line ending is not unix style, and I need to do the following commands to convert them in order to avoid the patch failures as the following.

Conversion command:
```
find . -type f | xargs dos2unix
```
Patch failures:
```
lordofire$ patch -p1 -d . -i ~/ping3_py.patch
patching file ping3/__init__.py
Hunk #1 FAILED at 229 (different line endings).
1 out of 1 hunk FAILED -- saving rejects to file ping3/__init__.py.rej
```

Could you please help rebuild the package with the above conversion command executed? Thanks.

**Comment by kyan001** [comment]
I have downloaded the code and checked the line endings. They are LF as expected. Please test it again with the latest version of the code. If the problem persists, feel free to reopen this issue and provide more details. Thank you for your feedback.
