### ISSUE TITLE
Dont work in 3.11.1

### ISSUE THREAD

**Issue by AlbertoCanoD** [kyan001/ping3#65]
Hello, i'm triying to install in 3.11.1 version, it seems what work but VisualStudio IDE dont recognize.

`Successfully installed ping3-4.0.4`

`ModuleNotFoundError: No module named 'ping3'`

In 3.10.9 version works perfectly.

**Comment by kyan001** [comment]
Hi @AlbertoCanoD,

I just tested again with ping3-4.0.4, everything is fine by `python -m pip` command. But I don't know what's going on on VisualStudio IDE, so it's maybe some IDE configuration problem?

**Comment by AlbertoCanoD** [comment]
I'm triying to import it directly in python.exe in 3.11.1 version, but also not work. 


![image](https://user-images.githubusercontent.com/55259915/216292322-18745f06-70ba-4d23-b01a-8f48def01a40.png)


Same method but 3.10.9 works fine.

**Comment by kyan001** [comment]
From your screenshot, the ping3 package is installed under “python310” folder.
Try `py -m pip install ping3`.

**Comment by AlbertoCanoD** [comment]
Thx, now works fine.
