### ISSUE TITLE
Not receiving low TTL response. Receiving Timeout instead.

### ISSUE THREAD

**Issue by mihaaairu** [kyan001/ping3#68]
Hello again! :) I've digged in your library and found, that it's not possible to obtain TTL-expired error. Receiving timeout instead. And, as i understood from your post on stackoverflow, windows stealing packets with expired TTL from raw socket ? 
Is there any updates with this problem?

**Comment by kyan001** [comment]
Why you said it's not possible to obtain TTL Expired Error? Is it a bug in code? Which line?

**Comment by MikhailChertkov** [comment]
There is debug for 1 package:
```
[DEBUG] Ping3 Version: 4.0.4
[DEBUG] LOGGER: <Logger ping3 (DEBUG)>
[DEBUG] Function called: verbose_ping({'dest_addr': '8.8.8.8', 'count': 1, 'interval': 1.0, 'timeout': 4.0, 'size': 32, 'ttl': 1})
[DEBUG] Function returned: verbose_ping -> <generator object verbose_ping at 0x0000029A25F78C10>
[DEBUG] Function called: ping(8.8.8.8, {'seq': 0, 'size': 32, 'timeout': 4.0, 'ttl': 1, 'unit': 'ms'})
[DEBUG] Set Socket Option `IP_TTL` in `SOL_IP` Failed: [WinError 10022] Получен недопустимый аргумент
[DEBUG] Function called: send_one_ping({'sock': <socket.socket fd=1000, family=AddressFamily.AF_INET, type=SocketKind.SOCK_RAW, proto=1>, 'dest_addr': '8.8.8.8', 'icmp_id': 64110, 'seq': 0, 'size': 32})
[DEBUG] Destination address: '8.8.8.8'
[DEBUG] Destination IP address: 8.8.8.8
[DEBUG] Sent ICMP header: {'type': 8, 'code': 0, 'checksum': 40811, 'id': 64110, 'seq': 0}
[DEBUG] Sent ICMP payload: b'A\xd9\x01y\x9c\x86\xae|QQQQQQQQQQQQQQQQQQQQQQQQ'
[DEBUG] Function returned: send_one_ping -> None
[DEBUG] Function called: receive_one_ping({'sock': <socket.socket fd=1000, family=AddressFamily.AF_INET, type=SocketKind.SOCK_RAW, proto=1, laddr=('0.0.0.0', 0)>, 'icmp_id': 64110, 'seq': 0, 'timeout': 4.0})
[DEBUG] Timeout time: Mon Mar  6 16:11:18 2023 (1678108278.1053994)
[DEBUG] Timeout left: 4.00s
[DEBUG] Function returned: ping -> Request timeout for ICMP packet. (Timeout=4.0s)
```

**Comment by kyan001** [comment]
> In **init**, line 212-218 (according to git repo). Obtaining Timeout with this request setup (timeout=4, ttl=1, packages=4, interval=1, payload=32, dest_addr=8.8.8.8). I tested higher TTL too. But always got two ways. 1st, I receive the response bc TTL was too hight, ans 2nd, I obtain timeout error, bc TTL was too low. Address can be different. I tested google.com, cisco.com, ya.ru, bing.com and some city's local addresses.

TTL Expired Error receiving is not affected by these codes. On Windows, you may not receive TTL Expired Errors due to the operating system limitation. On macOS, you can receive TTL Expired Errors as expected. On Unix and Linux, you need to use root privilege to receive TTL Expired Errors. Please make sure the host is able to send a TTL Expired Error when TTL = 0. Some host setups may not send back TTL Expired Errors at all.

**Comment by MikhailChertkov** [comment]
What's interesting, in `__init__`, on 289 line, in `ping()` method, it's impossible to pass this gate with TTL=0, so, if you try to modify that line like `if ttl >= 0:` you ll be able to receive TTL exceed error. But it will work for TTL=0 only. Every too small TTL above zero will cause Timeout again.

**Comment by kyan001** [comment]
> What's interesting, in `__init__`, on 289 line, in `ping()` method, it's impossible to pass this gate with TTL=0, so, if you try to modify that line like `if ttl >= 0:` you will be able to receive TTL exceed error. But it will work with TTL=0 only. Every too small TTL above zero will cause Timeout again.
> 
> But, in Debug every custom TTL request causes this error on 296 line.
> 
> ```
> [DEBUG] Function called: ping(8.8.8.8, {'seq': 0, 'size': 32, 'timeout': 4, 'ttl': 64, 'unit': 'ms'})
> [DEBUG] Set Socket Option `IP_TTL` in `SOL_IP` Failed: [WinError 10022] An invalid argument was supplied.
> ```
> 
> But, without setup ttl option via calling `verbose_ping`, i don't obtain this error.

ping() function is to send the request, the ttl expired error is for receiving.

**Comment by MikhailChertkov** [comment]
Yes, but when I send too low TTL, 5 as example, I have timeout instead of TTL Expired.

**Comment by MikhailChertkov** [comment]
But cmd ping return TTL expired error, when ping3 not. That's why I thought it's something with ping3 or sokets. I saw your comments in the code and understand, that windows steal packages with exceed ttl from sokets sometimes, but, you have asked about this issue about 5 years ago, on stackovreflow, so I thought something could change during this year's :)

**Comment by kyan001** [comment]
I tested again for this issue on my Windows 11. The TTL Exceeded packet still cannot be delivered to the raw socket.
