### ISSUE TITLE
Inconsistent cross-distro behavior

### ISSUE THREAD

**Issue by amyipdev** [kyan001/ping3#71]
On debian 12, a failed ping returns `False`, but on Fedora 38, it returns `None`. This is a breaking behavior and goes against the documentation as well as all rationality; becausse of the documentation, I was testing for `ping3.ping(host) is not None` but turns out that doesn't work because of this break.

**Comment by kyan001** [comment]
can you run the same cases in each platform with `ping3.DEBUG = True` and paste the outputs here?

**Comment by kyan001** [comment]
If `ping` returns `None`, it should be a timeout, which means there is no response. 
If `ping` return `False`, there is an Error during the ping, which means there is a response but the response says "Error Occurred".

Some platform will screen off the error responses if you do not run the program with root privilege. You can try to run this with root privilege to see if there is a difference.

**Comment by amyipdev** [comment]
@kyan001 surprisingly, running with `ping3.DEBUG = True`, they're both now returning the same value.

My guess is that this has to do with OS-level handling of DHUs. My Debian installation appears to be willing to call a DHU at times where my Fedora installation won't - if I makeup a nonsense IP, for instance, Fedora will not DHU, but Debian will. Debian's behavior is more erratic on previously-existing addresses, however.

**Comment by kyan001** [comment]
Yes, different systems will have different handling. Currently Ping3 only adapts to Windows, Linux and macOS.

**Comment by amyipdev** [comment]
@kyan001 debian and fedora are both linux distributions

**Comment by kyan001** [comment]
Yeah, I mean ping3 only uses different codes for different platforms, such as Linux, macOS and Windows. It doesn’t have any specific codes for different distributions within the same platform.
