### ISSUE TITLE
Incomplete type hints

### ISSUE THREAD

**Issue by n1colassilva** [kyan001/ping3#78]
Most functions don't indicate what they return, and ping specifically indicates it returns only `float`, but documentation and code indicated it can also return `None`  on timeouts and `false` on errors. This is a problem because and editor's type hinting wont indicate those possibilities, and when a dev adresses those use cases the editor will complain that `None` and `false` are not returned by `ping`

Pr #69 seems to adress these issues

**Comment by kyan001** [comment]
I will fix this problem asap.

**Comment by kyan001** [comment]
Type hints fixed with version 4.0.6.
