### ISSUE TITLE
better ways to mask icmp_id?

### ISSUE THREAD

**Issue by s3cy** [kyan001/ping3#8]
Greetings,

I am trying to do multi-threading on ping3. In your code: `threading.current_thread().ident` works okay and gives unique ids. However, `0xFFFF` becomes an issue. For example, `140395582191360 & 0xFFFF` is 63232 and `140395367364352 & 0xFFFF` is also 63232 :worried: . For some strange reason, this issue happens quite frequently on my manjaro linux machine (1 in 5 tries). How can I overcome? Thank you in advance.

**Comment by kyan001** [comment]
I'm looking into this problem.
Let's see if `ident % 0xffff` works.

**Comment by kyan001** [comment]
Updated in version 2.1.0
