### ISSUE TITLE
Ping to 127.0.0.1 shows "example.com"

### ISSUE THREAD

**Issue by stuaxo** [kyan001/ping3#9]
```bash
python -mping3 127.0.0.1

ping 'example.com' ... Timeout
```

**Comment by kyan001** [comment]
[Here](https://github.com/kyan001/ping3/blob/master/README.md#get-started) are some examples of usage. 

In you case, you just run the script itself, and pass a command-line argument to the script. Currently ping3 does not support command-line calls, but it will in the upcoming version.

Please check out `python -m  ping3 --help` for more info after you upgrade ping3 to `2.2.*`.
